from PyQt5.QtCore import QEvent
from .EnumManager import EnumManager

event_enum_manager = EnumManager(
    names=[
        "None_", "Timer", "MouseButtonPress", "MouseButtonRelease",
        "MouseButtonDblClick", "MouseMove", "KeyPress", "KeyRelease",
        "FocusIn", "FocusOut", "Enter", "Leave", "Paint", "Move", "Resize",
        "Show", "Hide", "Close", "ParentChange", "ParentAboutToChange",
        "ThreadChange", "WindowActivate", "WindowDeactivate", "ShowToParent",
        "HideToParent", "Wheel", "WindowTitleChange", "WindowIconChange",
        "ApplicationWindowIconChange", "ApplicationFontChange",
        "ApplicationLayoutDirectionChange", "ApplicationPaletteChange",
        "PaletteChange", "Clipboard", "MetaCall", "SockAct", "WinEventAct",
        "DeferredDelete", "DragEnter", "DragMove", "DragLeave", "Drop",
        "ChildAdded", "ChildPolished", "ChildRemoved", "PolishRequest",
        "Polish", "LayoutRequest", "UpdateRequest", "UpdateLater",
        "ContextMenu", "InputMethod", "TabletMove", "LocaleChange",
        "LanguageChange", "LayoutDirectionChange", "TabletPress",
        "TabletRelease", "OkRequest", "IconDrag", "FontChange",
        "EnabledChange", "ActivationChange", "StyleChange", "IconTextChange",
        "ModifiedChange", "MouseTrackingChange", "WindowBlocked",
        "WindowUnblocked", "WindowStateChange", "ToolTip", "WhatsThis",
        "StatusTip", "ActionChanged", "ActionAdded", "ActionRemoved",
        "FileOpen", "Shortcut", "ShortcutOverride", "WhatsThisClicked",
        "ToolBarChange", "ApplicationActivate", "ApplicationActivated",
        "ApplicationDeactivate", "ApplicationDeactivated", "QueryWhatsThis",
        "EnterWhatsThisMode", "LeaveWhatsThisMode", "ZOrderChange",
        "HoverEnter", "HoverLeave", "HoverMove", "GraphicsSceneMouseMove",
        "GraphicsSceneMousePress", "GraphicsSceneMouseRelease",
        "GraphicsSceneMouseDoubleClick", "GraphicsSceneContextMenu",
        "GraphicsSceneHoverEnter", "GraphicsSceneHoverMove",
        "GraphicsSceneHoverLeave", "GraphicsSceneHelp",
        "GraphicsSceneDragEnter", "GraphicsSceneDragMove",
        "GraphicsSceneDragLeave", "GraphicsSceneDrop", "GraphicsSceneWheel",
        "GraphicsSceneResize", "GraphicsSceneMove", "KeyboardLayoutChange",
        "DynamicPropertyChange", "TabletEnterProximity",
        "TabletLeaveProximity", "NonClientAreaMouseMove",
        "NonClientAreaMouseButtonPress", "NonClientAreaMouseButtonRelease",
        "NonClientAreaMouseButtonDblClick", "MacSizeChange",
        "ContentsRectChange", "CursorChange", "ToolTipChange", "GrabMouse",
        "UngrabMouse", "GrabKeyboard", "UngrabKeyboard", "StateMachineSignal",
        "StateMachineWrapped", "TouchBegin", "TouchUpdate", "TouchEnd",
        "RequestSoftwareInputPanel", "CloseSoftwareInputPanel", "WinIdChange",
        "Gesture", "GestureOverride", "FocusAboutToChange", "ScrollPrepare",
        "Scroll", "Expose", "InputMethodQuery", "OrientationChange",
        "TouchCancel", "PlatformPanel", "ApplicationStateChange",
        "ReadOnlyChange", "PlatformSurface", "TabletTrackingChange", "User",
        "MaxUser"
    ],
    values=[
        QEvent.Type.None_,
        QEvent.Type.Timer,
        QEvent.Type.MouseButtonPress,
        QEvent.Type.MouseButtonRelease,
        QEvent.Type.MouseButtonDblClick,
        QEvent.Type.MouseMove,
        QEvent.Type.KeyPress,
        QEvent.Type.KeyRelease,
        QEvent.Type.FocusIn,
        QEvent.Type.FocusOut,
        QEvent.Type.Enter,
        QEvent.Type.Leave,
        QEvent.Type.Paint,
        QEvent.Type.Move,
        QEvent.Type.Resize,
        QEvent.Type.Show,
        QEvent.Type.Hide,
        QEvent.Type.Close,
        QEvent.Type.ParentChange,
        QEvent.Type.ParentAboutToChange,
        QEvent.Type.ThreadChange,
        QEvent.Type.WindowActivate,
        QEvent.Type.WindowDeactivate,
        QEvent.Type.ShowToParent,
        QEvent.Type.HideToParent,
        QEvent.Type.Wheel,
        QEvent.Type.WindowTitleChange,
        QEvent.Type.WindowIconChange,
        QEvent.Type.ApplicationWindowIconChange,
        QEvent.Type.ApplicationFontChange,
        QEvent.Type.ApplicationLayoutDirectionChange,
        QEvent.Type.ApplicationPaletteChange,
        QEvent.Type.PaletteChange,
        QEvent.Type.Clipboard,
        QEvent.Type.MetaCall,
        QEvent.Type.SockAct,
        QEvent.Type.WinEventAct,
        QEvent.Type.DeferredDelete,
        QEvent.Type.DragEnter,
        QEvent.Type.DragMove,
        QEvent.Type.DragLeave,
        QEvent.Type.Drop,
        QEvent.Type.ChildAdded,
        QEvent.Type.ChildPolished,
        QEvent.Type.ChildRemoved,
        QEvent.Type.PolishRequest,
        QEvent.Type.Polish,
        QEvent.Type.LayoutRequest,
        QEvent.Type.UpdateRequest,
        QEvent.Type.UpdateLater,
        QEvent.Type.ContextMenu,
        QEvent.Type.InputMethod,
        QEvent.Type.TabletMove,
        QEvent.Type.LocaleChange,
        QEvent.Type.LanguageChange,
        QEvent.Type.LayoutDirectionChange,
        QEvent.Type.TabletPress,
        QEvent.Type.TabletRelease,
        QEvent.Type.OkRequest,
        QEvent.Type.IconDrag,
        QEvent.Type.FontChange,
        QEvent.Type.EnabledChange,
        QEvent.Type.ActivationChange,
        QEvent.Type.StyleChange,
        QEvent.Type.IconTextChange,
        QEvent.Type.ModifiedChange,
        QEvent.Type.MouseTrackingChange,
        QEvent.Type.WindowBlocked,
        QEvent.Type.WindowUnblocked,
        QEvent.Type.WindowStateChange,
        QEvent.Type.ToolTip,
        QEvent.Type.WhatsThis,
        QEvent.Type.StatusTip,
        QEvent.Type.ActionChanged,
        QEvent.Type.ActionAdded,
        QEvent.Type.ActionRemoved,
        QEvent.Type.FileOpen,
        QEvent.Type.Shortcut,
        QEvent.Type.ShortcutOverride,
        QEvent.Type.WhatsThisClicked,
        QEvent.Type.ToolBarChange,
        QEvent.Type.ApplicationActivate,
        QEvent.Type.ApplicationActivated,
        QEvent.Type.ApplicationDeactivate,
        QEvent.Type.ApplicationDeactivated,
        QEvent.Type.QueryWhatsThis,
        QEvent.Type.EnterWhatsThisMode,
        QEvent.Type.LeaveWhatsThisMode,
        QEvent.Type.ZOrderChange,
        QEvent.Type.HoverEnter,
        QEvent.Type.HoverLeave,
        QEvent.Type.HoverMove,
        QEvent.Type.GraphicsSceneMouseMove,
        QEvent.Type.GraphicsSceneMousePress,
        QEvent.Type.GraphicsSceneMouseRelease,
        QEvent.Type.GraphicsSceneMouseDoubleClick,
        QEvent.Type.GraphicsSceneContextMenu,
        QEvent.Type.GraphicsSceneHoverEnter,
        QEvent.Type.GraphicsSceneHoverMove,
        QEvent.Type.GraphicsSceneHoverLeave,
        QEvent.Type.GraphicsSceneHelp,
        QEvent.Type.GraphicsSceneDragEnter,
        QEvent.Type.GraphicsSceneDragMove,
        QEvent.Type.GraphicsSceneDragLeave,
        QEvent.Type.GraphicsSceneDrop,
        QEvent.Type.GraphicsSceneWheel,
        QEvent.Type.GraphicsSceneResize,
        QEvent.Type.GraphicsSceneMove,
        QEvent.Type.KeyboardLayoutChange,
        QEvent.Type.DynamicPropertyChange,
        QEvent.Type.TabletEnterProximity,
        QEvent.Type.TabletLeaveProximity,
        QEvent.Type.NonClientAreaMouseMove,
        QEvent.Type.NonClientAreaMouseButtonPress,
        QEvent.Type.NonClientAreaMouseButtonRelease,
        QEvent.Type.NonClientAreaMouseButtonDblClick,
        QEvent.Type.MacSizeChange,
        QEvent.Type.ContentsRectChange,
        QEvent.Type.CursorChange,
        QEvent.Type.ToolTipChange,
        QEvent.Type.GrabMouse,
        QEvent.Type.UngrabMouse,
        QEvent.Type.GrabKeyboard,
        QEvent.Type.UngrabKeyboard,
        QEvent.Type.StateMachineSignal,
        QEvent.Type.StateMachineWrapped,
        QEvent.Type.TouchBegin,
        QEvent.Type.TouchUpdate,
        QEvent.Type.TouchEnd,
        QEvent.Type.RequestSoftwareInputPanel,
        QEvent.Type.CloseSoftwareInputPanel,
        QEvent.Type.WinIdChange,
        QEvent.Type.Gesture,
        QEvent.Type.GestureOverride,
        QEvent.Type.FocusAboutToChange,
        QEvent.Type.ScrollPrepare,
        QEvent.Type.Scroll,
        QEvent.Type.Expose,
        QEvent.Type.InputMethodQuery,
        QEvent.Type.OrientationChange,
        QEvent.Type.TouchCancel,
        QEvent.Type.PlatformPanel,
        QEvent.Type.ApplicationStateChange,
        QEvent.Type.ReadOnlyChange,
        QEvent.Type.PlatformSurface,
        QEvent.Type.TabletTrackingChange,
        QEvent.Type.User,
        QEvent.Type.MaxUser,
    ])
