from PyQt5.QtCore import Qt
from .EnumManager import EnumManager

window_type_enum_manager = EnumManager(
    names=[
        "Widget", "Window", "Dialog", "Sheet", "Drawer", "Popup", "Tool",
        "ToolTip", "SplashScreen", "Desktop", "SubWindow", "WindowType_Mask",
        "MSWindowsFixedSizeDialogHint", "MSWindowsOwnDC",
        "X11BypassWindowManagerHint", "FramelessWindowHint",
        "CustomizeWindowHint", "WindowTitleHint", "WindowSystemMenuHint",
        "WindowMinimizeButtonHint", "WindowMaximizeButtonHint",
        "WindowMinMaxButtonsHint", "WindowContextHelpButtonHint",
        "WindowShadeButtonHint", "WindowStaysOnTopHint",
        "WindowStaysOnBottomHint", "WindowCloseButtonHint",
        "MacWindowToolBarButtonHint", "BypassGraphicsProxyWidget",
        "WindowTransparentForInput", "WindowOverridesSystemGestures",
        "WindowDoesNotAcceptFocus", "NoDropShadowWindowHint",
        "WindowFullscreenButtonHint", "ForeignWindow",
        "BypassWindowManagerHint", "CoverWindow",
        "MaximizeUsingFullscreenGeometryHint"
    ],
    values=[
        Qt.WindowType.Widget,
        Qt.WindowType.Window,
        Qt.WindowType.Dialog,
        Qt.WindowType.Sheet,
        Qt.WindowType.Drawer,
        Qt.WindowType.Popup,
        Qt.WindowType.Tool,
        Qt.WindowType.ToolTip,
        Qt.WindowType.SplashScreen,
        Qt.WindowType.Desktop,
        Qt.WindowType.SubWindow,
        Qt.WindowType.WindowType_Mask,
        Qt.WindowType.MSWindowsFixedSizeDialogHint,
        Qt.WindowType.MSWindowsOwnDC,
        Qt.WindowType.X11BypassWindowManagerHint,
        Qt.WindowType.FramelessWindowHint,
        Qt.WindowType.CustomizeWindowHint,
        Qt.WindowType.WindowTitleHint,
        Qt.WindowType.WindowSystemMenuHint,
        Qt.WindowType.WindowMinimizeButtonHint,
        Qt.WindowType.WindowMaximizeButtonHint,
        Qt.WindowType.WindowMinMaxButtonsHint,
        Qt.WindowType.WindowContextHelpButtonHint,
        Qt.WindowType.WindowShadeButtonHint,
        Qt.WindowType.WindowStaysOnTopHint,
        Qt.WindowType.WindowStaysOnBottomHint,
        Qt.WindowType.WindowCloseButtonHint,
        Qt.WindowType.MacWindowToolBarButtonHint,
        Qt.WindowType.BypassGraphicsProxyWidget,
        Qt.WindowType.WindowTransparentForInput,
        Qt.WindowType.WindowOverridesSystemGestures,
        Qt.WindowType.WindowDoesNotAcceptFocus,
        Qt.WindowType.NoDropShadowWindowHint,
        Qt.WindowType.WindowFullscreenButtonHint,
        Qt.WindowType.ForeignWindow,
        Qt.WindowType.BypassWindowManagerHint,
        Qt.WindowType.CoverWindow,
        Qt.WindowType.MaximizeUsingFullscreenGeometryHint,
    ])
